name: ondam
publish_to: 'none'

environment:
  sdk: ^3.12.2

workspace:
  - apps/senior
  - apps/guardian
  - packages/core
  - packages/design_system
  - packages/models
  - packages/network
  - packages/storage
  - packages/shared
